# Generated by Django 4.2.6 on 2023-10-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0002_trip_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='country',
        ),
    ]
