# Generated by Django 4.2.6 on 2023-10-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0003_rename_name_trip_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='cities_visited',
        ),
    ]
