# Generated by Django 4.2.6 on 2023-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0004_rename_description_trip_cities_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='visa',
            field=models.BooleanField(default=False),
        ),
    ]
