# Generated by Django 4.2.6 on 2023-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0005_flight_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='visa_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='visa_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
