# Generated by Django 4.2.6 on 2023-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0006_flight_visa_duration_flight_visa_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='visa_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='(in days)', null=True),
        ),
    ]
