# Generated by Django 4.2.6 on 2023-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0008_alter_flight_visa_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='visa_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(U.S. Dollar)', max_digits=10, null=True),
        ),
    ]
