# Generated by Django 4.2.6 on 2023-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanner', '0009_alter_flight_visa_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='visa_duration',
            field=models.IntegerField(blank=True, help_text='(in days)', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='visa_price',
            field=models.IntegerField(blank=True, help_text='(U.S. Dollar)', null=True),
        ),
    ]
